
name: Build and Publish
on:
  push:
    branches:
      - main
jobs:
  terraform-plan-and-apply:
    defaults:
      run:
        working-directory: ./terraform
    runs-on: ubuntu-latest
    env:
      GITHUB_OWNER: ukhomeoffice
      GITHUB_TOKEN: ${{ secrets.pat }}
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      id: init
      run: terraform init -reconfigure -backend-config="region=${{ secrets.tf_be_region }}" -backend-config="access_key=${{ secrets.tf_be_access_key }}"  -backend-config="secret_key=${{ secrets.tf_be_secret_key }}"

    - name: Terraform Validate
      id: validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve tfplan

